apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: http
    {{- if eq .Values.service.type "NodePort" }}
    {{- with .Values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
